
export interface ModuleBlueprint {
    codigo: string;
    descripcion: string;
    codigoPadre: string | null;
}

export const MODULE_BLUEPRINTS: ModuleBlueprint[] = [
    // Estructura Organizacional
    { codigo: 'organizational-structure', descripcion: 'Estructura Organizacional', codigoPadre: null },
    { codigo: 'companies', descripcion: 'Empresas', codigoPadre: 'organizational-structure' },
    { codigo: 'locations', descripcion: 'Ubicaciones', codigoPadre: 'organizational-structure' },
    { codigo: 'operating-units', descripcion: 'Unidades Operativas', codigoPadre: 'organizational-structure' },
    { codigo: 'patronal-records', descripcion: 'Registros Patronales', codigoPadre: 'organizational-structure' },
    { codigo: 'areas', descripcion: 'Areas Operativas', codigoPadre: 'organizational-structure' },
    { codigo: 'cost-center', descripcion: 'Centro de Costos', codigoPadre: 'organizational-structure' },
    { codigo: 'positions', descripcion: 'Puestos', codigoPadre: 'organizational-structure' },
    { codigo: 'salary-levels', descripcion: 'Niveles de Salario', codigoPadre: 'organizational-structure' },
    { codigo: 'validate-positions', descripcion: 'Validación de Puestos', codigoPadre: 'organizational-structure' },
    { codigo: 'headcount-ppto', descripcion: 'Plazas Operativas', codigoPadre: 'organizational-structure' },
    { codigo: 'authorized-organizational-chart', descripcion: 'Organigrama Autorizado', codigoPadre: 'organizational-structure' },
    { codigo: 'nominal-organization-chart', descripcion: 'Organigrama Nominal', codigoPadre: 'organizational-structure' },

    // Reclutamiento
    { codigo: 'recruitment', descripcion: 'Reclutamiento', codigoPadre: null },
    { codigo: 'requisitions', descripcion: 'Requisiciones', codigoPadre: 'recruitment' },
    { codigo: 'job-board', descripcion: 'Bolsa de trabajo', codigoPadre: 'recruitment' },
    { codigo: 'vacancies', descripcion: 'Vacantes', codigoPadre: 'recruitment' },
    { codigo: 'interviews', descripcion: 'Entrevistas', codigoPadre: 'recruitment' },

    // Expedientes digitales
    { codigo: 'digital-files', descripcion: 'Expedientes digitales', codigoPadre: null },
    { codigo: 'required-documents', descripcion: 'Documentos requeridos', codigoPadre: 'digital-files' },
    { codigo: 'case-files', descripcion: 'Expedientes', codigoPadre: 'digital-files' },
    { codigo: 'digital-contracts', descripcion: 'Contratos digitales', codigoPadre: 'digital-files' },
    { codigo: 'due-date-tracking', descripcion: 'Control de vencimientos', codigoPadre: 'digital-files' },

    // Administración de personal
    { codigo: 'personnel-administration', descripcion: 'Administración de personal', codigoPadre: null },
    { codigo: 'my-information', descripcion: 'Mi información', codigoPadre: 'personnel-administration' },
    { codigo: 'employees', descripcion: 'Empleados', codigoPadre: 'personnel-administration' },
    { codigo: 'incidents', descripcion: 'Incidencias', codigoPadre: 'personnel-administration' },
    { codigo: 'log-an-incident', descripcion: 'Levantar incidencia', codigoPadre: 'personnel-administration' },
    { codigo: 'internal-movements', descripcion: 'Movimientos internos', codigoPadre: 'personnel-administration' },
    { codigo: 'pending-requests', descripcion: 'Solicitudes pendientes', codigoPadre: 'personnel-administration' },

    // Control de asistencia
    { codigo: 'attendance-tracking', descripcion: 'Control de asistencia', codigoPadre: null },
    { codigo: 'my-attendance', descripcion: 'Mis asistencias', codigoPadre: 'attendance-tracking' },
    { codigo: 'attendance-dashboard', descripcion: 'Dashboard', codigoPadre: 'attendance-tracking' },
    { codigo: 'logbook', descripcion: 'Bitácora', codigoPadre: 'attendance-tracking' },
    { codigo: 'work-shifts', descripcion: 'Jornadas', codigoPadre: 'attendance-tracking' },
    { codigo: 'geofences', descripcion: 'Geocercas', codigoPadre: 'attendance-tracking' },
    { codigo: 'legal-workday', descripcion: 'Jornada legal', codigoPadre: 'attendance-tracking' },
    { codigo: 'attendance-configuration', descripcion: 'Configuración', codigoPadre: 'attendance-tracking' },

    // Capacitación
    { codigo: 'training', descripcion: 'Capacitación', codigoPadre: null },
    { codigo: 'courses', descripcion: 'Cursos', codigoPadre: 'training' },
    { codigo: 'job-courses', descripcion: 'Asignación por Puesto', codigoPadre: 'training' },
    { codigo: 'skills-matrix', descripcion: 'Matriz de Habilidades', codigoPadre: 'training' },
    { codigo: 'ai-roleplays', descripcion: 'Roleplays IA', codigoPadre: 'training' },
    { codigo: 'career-plan', descripcion: 'Plan de Carrera', codigoPadre: 'training' },

    // Configuración
    { codigo: 'configuration', descripcion: 'Configuración', codigoPadre: null },
    { codigo: 'roles-permissions', descripcion: 'Roles y permisos', codigoPadre: 'configuration' },
    { codigo: 'user-administration', descripcion: 'Admin. de usuarios', codigoPadre: 'configuration' },
    { codigo: 'integrations', descripcion: 'Integraciones', codigoPadre: 'configuration' },
    { codigo: 'approval-assignments', descripcion: 'Aprobadores', codigoPadre: 'configuration' },
    { codigo: 'document-templates', descripcion: 'Plantillas Documentos', codigoPadre: 'configuration' },
    { codigo: 'document-templates-generated', descripcion: 'Documentos Generados', codigoPadre: 'configuration' },
    { codigo: 'career-plan-config', descripcion: 'Plan de Carrera Conf', codigoPadre: 'configuration' },
];

export const ROLE_NAMES = ['Admin', 'RH', 'Finanzas', 'Reclutador', 'Manager', 'Empleado'];

export interface PermissionBlueprint {
    rolName: string;
    moduloCodigo: string;
    puedeVer: boolean;
    puedeCrear: boolean;
    puedeActualizar: boolean;
    puedeEliminar: boolean;
}

export const PERMISSION_BLUEPRINTS: PermissionBlueprint[] = [
    // =========================================================================
    // ROL: ADMIN (Acceso total a todos los módulos)
    // =========================================================================
    { rolName: 'Admin', moduloCodigo: 'organizational-structure', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: true },
    { rolName: 'Admin', moduloCodigo: 'companies', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: true },
    { rolName: 'Admin', moduloCodigo: 'locations', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: true },
    { rolName: 'Admin', moduloCodigo: 'operating-units', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: true },
    { rolName: 'Admin', moduloCodigo: 'patronal-records', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: true },
    { rolName: 'Admin', moduloCodigo: 'areas', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: true },
    { rolName: 'Admin', moduloCodigo: 'cost-center', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: true },
    { rolName: 'Admin', moduloCodigo: 'positions', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: true },
    { rolName: 'Admin', moduloCodigo: 'salary-levels', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: true },
    { rolName: 'Admin', moduloCodigo: 'validate-positions', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: true },
    { rolName: 'Admin', moduloCodigo: 'headcount-ppto', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: true },
    { rolName: 'Admin', moduloCodigo: 'authorized-organizational-chart', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: true },
    { rolName: 'Admin', moduloCodigo: 'nominal-organization-chart', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: true },
    { rolName: 'Admin', moduloCodigo: 'recruitment', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: true },
    { rolName: 'Admin', moduloCodigo: 'requisitions', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: true },
    { rolName: 'Admin', moduloCodigo: 'job-board', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: true },
    { rolName: 'Admin', moduloCodigo: 'vacancies', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: true },
    { rolName: 'Admin', moduloCodigo: 'interviews', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: true },
    { rolName: 'Admin', moduloCodigo: 'digital-files', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: true },
    { rolName: 'Admin', moduloCodigo: 'required-documents', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: true },
    { rolName: 'Admin', moduloCodigo: 'case-files', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: true },
    { rolName: 'Admin', moduloCodigo: 'digital-contracts', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: true },
    { rolName: 'Admin', moduloCodigo: 'due-date-tracking', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: true },
    { rolName: 'Admin', moduloCodigo: 'personnel-administration', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: true },
    { rolName: 'Admin', moduloCodigo: 'my-information', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: true },
    { rolName: 'Admin', moduloCodigo: 'employees', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: true },
    { rolName: 'Admin', moduloCodigo: 'incidents', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: true },
    { rolName: 'Admin', moduloCodigo: 'log-an-incident', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: true },
    { rolName: 'Admin', moduloCodigo: 'internal-movements', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: true },
    { rolName: 'Admin', moduloCodigo: 'pending-requests', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: true },
    { rolName: 'Admin', moduloCodigo: 'attendance-tracking', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: true },
    { rolName: 'Admin', moduloCodigo: 'my-attendance', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: true },
    { rolName: 'Admin', moduloCodigo: 'attendance-dashboard', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: true },
    { rolName: 'Admin', moduloCodigo: 'logbook', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: true },
    { rolName: 'Admin', moduloCodigo: 'work-shifts', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: true },
    { rolName: 'Admin', moduloCodigo: 'geofences', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: true },
    { rolName: 'Admin', moduloCodigo: 'legal-workday', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: true },
    { rolName: 'Admin', moduloCodigo: 'attendance-configuration', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: true },
    { rolName: 'Admin', moduloCodigo: 'training', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: true },
    { rolName: 'Admin', moduloCodigo: 'courses', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: true },
    { rolName: 'Admin', moduloCodigo: 'job-courses', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: true },
    { rolName: 'Admin', moduloCodigo: 'skills-matrix', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: true },
    { rolName: 'Admin', moduloCodigo: 'ai-roleplays', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: true },
    { rolName: 'Admin', moduloCodigo: 'career-plan', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: true },
    { rolName: 'Admin', moduloCodigo: 'configuration', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: true },
    { rolName: 'Admin', moduloCodigo: 'roles-permissions', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: true },
    { rolName: 'Admin', moduloCodigo: 'user-administration', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: true },
    { rolName: 'Admin', moduloCodigo: 'integrations', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: true },
    { rolName: 'Admin', moduloCodigo: 'approval-assignments', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: true },
    { rolName: 'Admin', moduloCodigo: 'document-templates', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: true },
    { rolName: 'Admin', moduloCodigo: 'document-templates-generated', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: true },
    { rolName: 'Admin', moduloCodigo: 'career-plan-config', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: true },

    // =========================================================================
    // ROL: RH
    // =========================================================================
    { rolName: 'RH', moduloCodigo: 'organizational-structure', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'RH', moduloCodigo: 'companies', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'RH', moduloCodigo: 'locations', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'RH', moduloCodigo: 'operating-units', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'RH', moduloCodigo: 'patronal-records', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'RH', moduloCodigo: 'areas', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'RH', moduloCodigo: 'cost-center', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'RH', moduloCodigo: 'positions', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'RH', moduloCodigo: 'salary-levels', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'RH', moduloCodigo: 'validate-positions', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'RH', moduloCodigo: 'headcount-ppto', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'RH', moduloCodigo: 'authorized-organizational-chart', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'RH', moduloCodigo: 'nominal-organization-chart', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'RH', moduloCodigo: 'recruitment', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'RH', moduloCodigo: 'requisitions', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: true },
    { rolName: 'RH', moduloCodigo: 'job-board', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'RH', moduloCodigo: 'vacancies', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'RH', moduloCodigo: 'interviews', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'RH', moduloCodigo: 'digital-files', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'RH', moduloCodigo: 'required-documents', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'RH', moduloCodigo: 'case-files', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'RH', moduloCodigo: 'digital-contracts', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'RH', moduloCodigo: 'due-date-tracking', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'RH', moduloCodigo: 'personnel-administration', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'RH', moduloCodigo: 'my-information', puedeVer: true, puedeCrear: false, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'RH', moduloCodigo: 'employees', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'RH', moduloCodigo: 'incidents', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'RH', moduloCodigo: 'log-an-incident', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'RH', moduloCodigo: 'internal-movements', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'RH', moduloCodigo: 'pending-requests', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'RH', moduloCodigo: 'attendance-tracking', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'RH', moduloCodigo: 'my-attendance', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'RH', moduloCodigo: 'attendance-dashboard', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'RH', moduloCodigo: 'logbook', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'RH', moduloCodigo: 'work-shifts', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'RH', moduloCodigo: 'geofences', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'RH', moduloCodigo: 'legal-workday', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'RH', moduloCodigo: 'attendance-configuration', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'RH', moduloCodigo: 'training', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'RH', moduloCodigo: 'courses', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'RH', moduloCodigo: 'job-courses', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'RH', moduloCodigo: 'skills-matrix', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'RH', moduloCodigo: 'ai-roleplays', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'RH', moduloCodigo: 'career-plan', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'RH', moduloCodigo: 'configuration', puedeVer: true, puedeCrear: false, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'RH', moduloCodigo: 'roles-permissions', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'RH', moduloCodigo: 'user-administration', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'RH', moduloCodigo: 'integrations', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'RH', moduloCodigo: 'approval-assignments', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'RH', moduloCodigo: 'document-templates', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'RH', moduloCodigo: 'document-templates-generated', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'RH', moduloCodigo: 'career-plan-config', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: false },

    // =========================================================================
    // ROL: FINANZAS
    // =========================================================================
    { rolName: 'Finanzas', moduloCodigo: 'organizational-structure', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Finanzas', moduloCodigo: 'companies', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Finanzas', moduloCodigo: 'locations', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Finanzas', moduloCodigo: 'operating-units', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Finanzas', moduloCodigo: 'patronal-records', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Finanzas', moduloCodigo: 'areas', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Finanzas', moduloCodigo: 'cost-center', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Finanzas', moduloCodigo: 'positions', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Finanzas', moduloCodigo: 'salary-levels', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Finanzas', moduloCodigo: 'validate-positions', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Finanzas', moduloCodigo: 'headcount-ppto', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Finanzas', moduloCodigo: 'authorized-organizational-chart', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Finanzas', moduloCodigo: 'nominal-organization-chart', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Finanzas', moduloCodigo: 'recruitment', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Finanzas', moduloCodigo: 'requisitions', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Finanzas', moduloCodigo: 'job-board', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Finanzas', moduloCodigo: 'vacancies', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Finanzas', moduloCodigo: 'interviews', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Finanzas', moduloCodigo: 'digital-files', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Finanzas', moduloCodigo: 'required-documents', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Finanzas', moduloCodigo: 'case-files', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Finanzas', moduloCodigo: 'digital-contracts', puedeVer: true, puedeCrear: false, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'Finanzas', moduloCodigo: 'due-date-tracking', puedeVer: true, puedeCrear: false, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'Finanzas', moduloCodigo: 'personnel-administration', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Finanzas', moduloCodigo: 'my-information', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Finanzas', moduloCodigo: 'employees', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Finanzas', moduloCodigo: 'incidents', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Finanzas', moduloCodigo: 'log-an-incident', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Finanzas', moduloCodigo: 'internal-movements', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Finanzas', moduloCodigo: 'pending-requests', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Finanzas', moduloCodigo: 'attendance-tracking', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Finanzas', moduloCodigo: 'my-attendance', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Finanzas', moduloCodigo: 'attendance-dashboard', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Finanzas', moduloCodigo: 'logbook', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Finanzas', moduloCodigo: 'work-shifts', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Finanzas', moduloCodigo: 'geofences', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Finanzas', moduloCodigo: 'legal-workday', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Finanzas', moduloCodigo: 'attendance-configuration', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Finanzas', moduloCodigo: 'training', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Finanzas', moduloCodigo: 'courses', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Finanzas', moduloCodigo: 'job-courses', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Finanzas', moduloCodigo: 'skills-matrix', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Finanzas', moduloCodigo: 'ai-roleplays', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Finanzas', moduloCodigo: 'career-plan', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Finanzas', moduloCodigo: 'configuration', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Finanzas', moduloCodigo: 'roles-permissions', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Finanzas', moduloCodigo: 'user-administration', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Finanzas', moduloCodigo: 'integrations', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Finanzas', moduloCodigo: 'approval-assignments', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Finanzas', moduloCodigo: 'document-templates', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Finanzas', moduloCodigo: 'document-templates-generated', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Finanzas', moduloCodigo: 'career-plan-config', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },

    // =========================================================================
    // ROL: RECLUTADOR
    // =========================================================================
    { rolName: 'Reclutador', moduloCodigo: 'organizational-structure', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Reclutador', moduloCodigo: 'companies', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Reclutador', moduloCodigo: 'locations', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Reclutador', moduloCodigo: 'operating-units', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Reclutador', moduloCodigo: 'patronal-records', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Reclutador', moduloCodigo: 'areas', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Reclutador', moduloCodigo: 'cost-center', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Reclutador', moduloCodigo: 'positions', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Reclutador', moduloCodigo: 'salary-levels', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Reclutador', moduloCodigo: 'validate-positions', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Reclutador', moduloCodigo: 'headcount-ppto', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Reclutador', moduloCodigo: 'authorized-organizational-chart', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Reclutador', moduloCodigo: 'nominal-organization-chart', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Reclutador', moduloCodigo: 'recruitment', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: true },
    { rolName: 'Reclutador', moduloCodigo: 'requisitions', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'Reclutador', moduloCodigo: 'job-board', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: true },
    { rolName: 'Reclutador', moduloCodigo: 'vacancies', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: true },
    { rolName: 'Reclutador', moduloCodigo: 'interviews', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: true },
    { rolName: 'Reclutador', moduloCodigo: 'digital-files', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Reclutador', moduloCodigo: 'required-documents', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Reclutador', moduloCodigo: 'case-files', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Reclutador', moduloCodigo: 'digital-contracts', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Reclutador', moduloCodigo: 'due-date-tracking', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Reclutador', moduloCodigo: 'personnel-administration', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Reclutador', moduloCodigo: 'my-information', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Reclutador', moduloCodigo: 'employees', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Reclutador', moduloCodigo: 'incidents', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Reclutador', moduloCodigo: 'log-an-incident', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Reclutador', moduloCodigo: 'internal-movements', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Reclutador', moduloCodigo: 'pending-requests', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Reclutador', moduloCodigo: 'attendance-tracking', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Reclutador', moduloCodigo: 'my-attendance', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Reclutador', moduloCodigo: 'attendance-dashboard', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Reclutador', moduloCodigo: 'logbook', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Reclutador', moduloCodigo: 'work-shifts', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Reclutador', moduloCodigo: 'geofences', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Reclutador', moduloCodigo: 'legal-workday', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Reclutador', moduloCodigo: 'attendance-configuration', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Reclutador', moduloCodigo: 'training', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Reclutador', moduloCodigo: 'courses', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Reclutador', moduloCodigo: 'job-courses', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Reclutador', moduloCodigo: 'skills-matrix', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Reclutador', moduloCodigo: 'ai-roleplays', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Reclutador', moduloCodigo: 'career-plan', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Reclutador', moduloCodigo: 'configuration', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Reclutador', moduloCodigo: 'roles-permissions', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Reclutador', moduloCodigo: 'user-administration', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Reclutador', moduloCodigo: 'integrations', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Reclutador', moduloCodigo: 'approval-assignments', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Reclutador', moduloCodigo: 'document-templates', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'Reclutador', moduloCodigo: 'document-templates-generated', puedeVer: true, puedeCrear: true, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Reclutador', moduloCodigo: 'career-plan-config', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },

    // =========================================================================
    // ROL: MANAGER
    // =========================================================================
    { rolName: 'Manager', moduloCodigo: 'organizational-structure', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Manager', moduloCodigo: 'companies', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Manager', moduloCodigo: 'locations', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Manager', moduloCodigo: 'operating-units', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Manager', moduloCodigo: 'patronal-records', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Manager', moduloCodigo: 'areas', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Manager', moduloCodigo: 'cost-center', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Manager', moduloCodigo: 'positions', puedeVer: true, puedeCrear: false, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'Manager', moduloCodigo: 'salary-levels', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Manager', moduloCodigo: 'validate-positions', puedeVer: true, puedeCrear: false, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'Manager', moduloCodigo: 'headcount-ppto', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Manager', moduloCodigo: 'authorized-organizational-chart', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Manager', moduloCodigo: 'nominal-organization-chart', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Manager', moduloCodigo: 'recruitment', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Manager', moduloCodigo: 'requisitions', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: true },
    { rolName: 'Manager', moduloCodigo: 'job-board', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Manager', moduloCodigo: 'vacancies', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Manager', moduloCodigo: 'interviews', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Manager', moduloCodigo: 'digital-files', puedeVer: true, puedeCrear: false, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'Manager', moduloCodigo: 'required-documents', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Manager', moduloCodigo: 'case-files', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Manager', moduloCodigo: 'digital-contracts', puedeVer: true, puedeCrear: false, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'Manager', moduloCodigo: 'due-date-tracking', puedeVer: true, puedeCrear: false, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'Manager', moduloCodigo: 'personnel-administration', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'Manager', moduloCodigo: 'my-information', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Manager', moduloCodigo: 'employees', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Manager', moduloCodigo: 'incidents', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'Manager', moduloCodigo: 'log-an-incident', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'Manager', moduloCodigo: 'internal-movements', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'Manager', moduloCodigo: 'pending-requests', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'Manager', moduloCodigo: 'attendance-tracking', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Manager', moduloCodigo: 'my-attendance', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Manager', moduloCodigo: 'attendance-dashboard', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Manager', moduloCodigo: 'logbook', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Manager', moduloCodigo: 'work-shifts', puedeVer: true, puedeCrear: false, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'Manager', moduloCodigo: 'geofences', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Manager', moduloCodigo: 'legal-workday', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Manager', moduloCodigo: 'attendance-configuration', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Manager', moduloCodigo: 'training', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'Manager', moduloCodigo: 'courses', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Manager', moduloCodigo: 'job-courses', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'Manager', moduloCodigo: 'skills-matrix', puedeVer: true, puedeCrear: false, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'Manager', moduloCodigo: 'ai-roleplays', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Manager', moduloCodigo: 'career-plan', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'Manager', moduloCodigo: 'configuration', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Manager', moduloCodigo: 'roles-permissions', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Manager', moduloCodigo: 'user-administration', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Manager', moduloCodigo: 'integrations', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Manager', moduloCodigo: 'approval-assignments', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Manager', moduloCodigo: 'document-templates', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Manager', moduloCodigo: 'document-templates-generated', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Manager', moduloCodigo: 'career-plan-config', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },

    // =========================================================================
    // ROL: EMPLEADO
    // =========================================================================
    { rolName: 'Empleado', moduloCodigo: 'organizational-structure', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Empleado', moduloCodigo: 'companies', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Empleado', moduloCodigo: 'locations', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Empleado', moduloCodigo: 'operating-units', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Empleado', moduloCodigo: 'patronal-records', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Empleado', moduloCodigo: 'areas', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Empleado', moduloCodigo: 'cost-center', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Empleado', moduloCodigo: 'positions', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Empleado', moduloCodigo: 'salary-levels', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Empleado', moduloCodigo: 'validate-positions', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Empleado', moduloCodigo: 'headcount-ppto', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Empleado', moduloCodigo: 'authorized-organizational-chart', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Empleado', moduloCodigo: 'nominal-organization-chart', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Empleado', moduloCodigo: 'recruitment', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Empleado', moduloCodigo: 'requisitions', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Empleado', moduloCodigo: 'job-board', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Empleado', moduloCodigo: 'vacancies', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Empleado', moduloCodigo: 'interviews', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Empleado', moduloCodigo: 'digital-files', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Empleado', moduloCodigo: 'required-documents', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Empleado', moduloCodigo: 'case-files', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Empleado', moduloCodigo: 'digital-contracts', puedeVer: false, puedeCrear: false, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'Empleado', moduloCodigo: 'due-date-tracking', puedeVer: false, puedeCrear: false, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'Empleado', moduloCodigo: 'personnel-administration', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Empleado', moduloCodigo: 'my-information', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Empleado', moduloCodigo: 'employees', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Empleado', moduloCodigo: 'incidents', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Empleado', moduloCodigo: 'log-an-incident', puedeVer: true, puedeCrear: true, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Empleado', moduloCodigo: 'internal-movements', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Empleado', moduloCodigo: 'pending-requests', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Empleado', moduloCodigo: 'attendance-tracking', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Empleado', moduloCodigo: 'my-attendance', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Empleado', moduloCodigo: 'attendance-dashboard', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Empleado', moduloCodigo: 'logbook', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Empleado', moduloCodigo: 'work-shifts', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Empleado', moduloCodigo: 'geofences', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Empleado', moduloCodigo: 'legal-workday', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Empleado', moduloCodigo: 'attendance-configuration', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Empleado', moduloCodigo: 'training', puedeVer: true, puedeCrear: false, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'Empleado', moduloCodigo: 'courses', puedeVer: true, puedeCrear: false, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'Empleado', moduloCodigo: 'job-courses', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Empleado', moduloCodigo: 'skills-matrix', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Empleado', moduloCodigo: 'ai-roleplays', puedeVer: true, puedeCrear: true, puedeActualizar: true, puedeEliminar: false },
    { rolName: 'Empleado', moduloCodigo: 'career-plan', puedeVer: true, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Empleado', moduloCodigo: 'configuration', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Empleado', moduloCodigo: 'roles-permissions', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Empleado', moduloCodigo: 'user-administration', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Empleado', moduloCodigo: 'integrations', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Empleado', moduloCodigo: 'approval-assignments', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Empleado', moduloCodigo: 'document-templates', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Empleado', moduloCodigo: 'document-templates-generated', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
    { rolName: 'Empleado', moduloCodigo: 'career-plan-config', puedeVer: false, puedeCrear: false, puedeActualizar: false, puedeEliminar: false },
];